Repository DonggeonOh/bithumb-techcamp-ios-1st, pull requests merged in 2022-03, with the labels that each got.

#32 WebSocket model 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Model/BithumbPublicAPI/GETMethod/GETMethods.swift
  BithumbYagomAcamedy/Network/HTTP/Extension/URLRequest+extension.swift
  BithumbYagomAcamedy/Network/HTTP/Extension/URLSession+extension.swift
  BithumbYagomAcamedy/Network/HTTP/HTTPNetworkService.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/AssetsStatusAPI.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/OrderbookAPI.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/TickerAPI.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/TransactionHistoryAPI.swift
  BithumbYagomAcamedy/Network/HTTP/Model/BithumbPublicAPIURL.swift
  BithumbYagomAcamedy/Network/HTTP/Protocol/APIable.swift
  BithumbYagomAcamedy/Network/HTTP/Protocol/BaseURLable.swift
  BithumbYagomAcamedy/Network/WebSocket/Extension/URLSessionWebSocketTask+extension.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/BithumbWebSocketURL.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/WebSocketMessageConverter.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/WebSocketModels/OrderBookDepth.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/WebSocketModels/TickerWebSocket.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/WebSocketModels/TransactionWebSocket.swift
  BithumbYagomAcamedy/Network/WebSocket/Protocol/WebSocketServicable.swift
  BithumbYagomAcamedy/Network/WebSocket/Protocol/WebSocketable.swift
  BithumbYagomAcamedy/Network/WebSocket/WebSocketService.swift
Labels: feat

#34 Network 리팩터링
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/Network/WebSocket/Protocol/WebSocketServicable.swift
  BithumbYagomAcamedy/Network/WebSocket/WebSocketService.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockWebSocketService.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockWebSocketURLSessionTask.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/NetworkServiceTests.swift
Labels: refactor

#46 코인 디테일 뷰 초기 설정 (공통 작업)
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/View/Base.lproj/MainTabBar.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinChartView/CoinChart.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetail.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPageView/CoinDetailPage.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPageView/CoinDetailPageViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbook.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransaction.storyboard
  BithumbYagomAcamedy/View/CoinListView/CoinList.storyboard
Labels: ui, feat

#40 입출금 현황 화면 검색, 필터, 정렬 기능 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/Model/AssetsStatus.swift
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_all_gray.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_all_gray.imageset/chevron_all_gray.png
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_under_black.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_under_black.imageset/chevron_under_black.png
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_up_black.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/SortImage/chevron_up_black.imageset/chevron_up_black.png
  BithumbYagomAcamedy/Resource/Assets.xcassets/StatusColor/SortStatusColor.colorset/Contents.json
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalStatus.storyboard
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/SortButton.swift
Labels: ui, feat

#43 채결 내역 셀 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Model/Transaction.swift
  BithumbYagomAcamedy/Model/ValueObject/TransactionValueObject.swift
  BithumbYagomAcamedy/Model/WebSockerValueObject/WebSocketTransactionValueObject.swift
  BithumbYagomAcamedy/View/TransactionView/TransactionCollectionViewCell.swift
  BithumbYagomAcamedy/View/TransactionView/TransactionCollectionViewCell.xib
Labels: ui, feat

#51 채결 내역 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Extension/Result+extension.swift
  BithumbYagomAcamedy/Model/Transaction.swift
  BithumbYagomAcamedy/Model/WebSockerValueObject/WebSocketTransactionValueObject.swift
  BithumbYagomAcamedy/Utility/JSONParser.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransaction.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionCollectionViewCell.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionCollectionViewCell.xib
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionViewController.swift
Labels: ui, feat

#54 입출금 현황 컬렉션 뷰 셀 레이아웃 수정 및 소문자 검색 기능 추가
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/Resource/en.lproj/Localizable.strings
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.xib
Labels: ui, fix, feat

#57 코인 상세 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Extension/Array+extension.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetail.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailMenuStackView.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPageView/CoinDetailPageViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPriceView.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailTitleButton.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/DetailViewCoin.swift
Labels: ui, feat

#56 그래프 차트 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy.xcodeproj/xcuserdata/ohdonggeon.xcuserdatad/xcschemes/xcschememanagement.plist
  BithumbYagomAcamedy/Controller/CoinChartViewController.swift
  BithumbYagomAcamedy/Model/Candlestick.swift
  BithumbYagomAcamedy/Model/CoinCandleChartDataEntry.swift
  BithumbYagomAcamedy/Model/CoinCandleChartDataSet.swift
  BithumbYagomAcamedy/Model/CoinChartDataManager.swift
  BithumbYagomAcamedy/Model/DateFormat.swift
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/Model/ValueObject/CandlestickValueObject.swift
  BithumbYagomAcamedy/Model/WebSocketValueObject/WebSocketOrderBookDepthValueObject.swift
  BithumbYagomAcamedy/Model/WebSocketValueObject/WebSocketTickerValueObject.swift
  BithumbYagomAcamedy/Model/WebSocketValueObject/WebSocketTransactionValueObject.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/CandlestickAPI.swift
  BithumbYagomAcamedy/Network/WebSocket/Model/Mock/MockCandlestickDataHour1.json
  BithumbYagomAcamedy/Network/WebSocket/Model/Mock/MockCandlestickDataHour24.json
  BithumbYagomAcamedy/Network/WebSocket/Model/Mock/MockCandlestickDataMinute1.json
  BithumbYagomAcamedy/Network/WebSocket/Model/Mock/MockCandlestickDataMinute10.json
  BithumbYagomAcamedy/Network/WebSocket/Model/Mock/MockCandlestickDataMinute30.json
  BithumbYagomAcamedy/Network/WebSocket/Model/WebSocketModels/TickerWebSocket.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinChartView/CoinChart.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailDataManager.swift
  BithumbYagomAcamedyTests/JSONParserTest/JSONParserTests.swift
Labels: ui, feat

#58 코인 리스트 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/Coin.swift
  BithumbYagomAcamedy/Controller/CoinListDataManager.swift
  BithumbYagomAcamedy/Controller/CoinListMenuStackView.swift
  BithumbYagomAcamedy/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/View/CoinListView/CoinList.storyboard
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.swift
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.xib
Labels: feat

#66 입출금 필터링 검색 및 정렬 버그 수정 및 엔터 입력 시 키보드 숨김 기능 추가 #64
  BithumbYagomAcamedy/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
Labels: bug, feat

#65 코인 상세 화면 우측 상단 차트 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetail.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailChartImageView.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailViewController.swift
Labels: ui, feat

#61 코인 호가 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/Coin.swift
  BithumbYagomAcamedy/Extension/Double+extension.swift
  BithumbYagomAcamedy/Model/Orderbook.swift
  BithumbYagomAcamedy/Model/Transaction.swift
  BithumbYagomAcamedy/Model/ValueObject/OrderbookValueObject.swift
  BithumbYagomAcamedy/Model/WebSocketValueObject/WebSocketOrderBookDepthValueObject.swift
  BithumbYagomAcamedy/Network/HTTP/Model/APIModels/OrderbookAPI.swift
  BithumbYagomAcamedy/Resource/Assets.xcassets/OrderbookColor/Ask.colorset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/OrderbookColor/Bid.colorset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/OrderbookColor/Contents.json
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbook.storyboard
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookCollectionViewCell.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookCollectionViewCell.xib
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/ShadowView.swift
  BithumbYagomAcamedy/View/CoinDetailView/DetailViewCoin.swift
Labels: ui, feat

#68 인기순 말풍선 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/View/CoinListView/BallonSpeakView.swift
  BithumbYagomAcamedy/View/CoinListView/CoinList.storyboard
Labels: ui, feat

#71 Core Data 엔티티 설계 및 초기화
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/AppLifeCycle/AppDelegate.swift
  BithumbYagomAcamedy/AppLifeCycle/SceneDelegate.swift
  BithumbYagomAcamedy/Model/CoreData/CandlestickChart+CoreDataClass.swift
  BithumbYagomAcamedy/Model/CoreData/CandlestickChart+CoreDataProperties.swift
  BithumbYagomAcamedy/Model/CoreData/CoreDataManager.swift
  BithumbYagomAcamedy/Model/CoreData/FavoriteCoin+CoreDataClass.swift
  BithumbYagomAcamedy/Model/CoreData/FavoriteCoin+CoreDataProperties.swift
  BithumbYagomAcamedy/Resource/BithumbYagomAcamedy.xcdatamodeld/BithumbYagomAcamedy.xcdatamodel/contents
Labels: feat

#76 입출금 현황 화면 최상단 스크롤 구현 및 스크롤 바 위치 수정
  BithumbYagomAcamedy/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalStatus.storyboard
Labels: ui, fix, feat

#77 화면 전환시 데이터 전달 방법
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/CoinChartViewController.swift
  BithumbYagomAcamedy/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/Protocol/ViewControllerInstantiatable.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/ViewControllerInstantiater.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/ViewInstantiateInformations/CoinChartViewInstantiateInformation.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/ViewInstantiateInformations/CoinDetailViewInstantiateInformation.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/ViewInstantiateInformations/CoinOrderbookViewInstantiateInformation.swift
  BithumbYagomAcamedy/Model/ViewControllerInstantiater/ViewInstantiateInformations/CoinTransactionViewInstantiateInformation.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPageView/CoinDetailPageViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailPageView/PageViewControllerable.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinDetailViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbokDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinOrderbookView/CoinOrderbookViewController.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionDataManager.swift
  BithumbYagomAcamedy/View/CoinDetailView/CoinTransactionView/CoinTransactionViewController.swift
Labels: feat

#84 코인리스트 정렬 탭 피그마디자인으로 수정
  BithumbYagomAcamedy/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/View/CoinListView/CoinList.storyboard
Labels: fix

#78 코인 차트 그래프 Core Data 로컬 데이터로 관리하는 기능 추가
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Model/Candlestick.swift
  BithumbYagomAcamedy/Model/ChartDateFormat.swift
  BithumbYagomAcamedy/Model/CoinChartCoreDataManager.swift
  BithumbYagomAcamedy/Model/CoinChartDataManager.swift
  BithumbYagomAcamedy/Model/CoreData/CandlestickChart+CoreDataClass.swift
  BithumbYagomAcamedy/Model/CoreData/CandlestickChart+CoreDataProperties.swift
  BithumbYagomAcamedy/Model/CoreData/CoreDataManager.swift
Labels: feat

#85 코인 그래프 화면의 줌 스케일 최적화 및 차트 화면 다크모드 적용
  BithumbYagomAcamedy/Controller/CoinChartViewController.swift
  BithumbYagomAcamedy/Model/CoinCandleChartDataSet.swift
Labels: ui, feat

#88 feat: 입출금 화면 초기에 이름순으로 정렬하여 데이터 표시 #87
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Common/View/SortButton.swift
  BithumbYagomAcamedy/DepositWithdrawalStatusScreen/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/DepositWithdrawalStatusScreen/Model/DepositWithdrawalStatusDataManager.swift
Labels: feat

#92 코인 상세 화면 우측 상단 차트 코어 데이터 적용
  BithumbYagomAcamedy/CoinDetailScreen/Controller/CoinDetailViewController.swift
  BithumbYagomAcamedy/CoinDetailScreen/Model/CoinDetailDataManager.swift
Labels: ui, feat

#91 코인 그래프에서 캔들스틱 터치 시 정보 표시 기능 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/CandlestickChartScreen/Controller/CoinChartViewController.swift
  BithumbYagomAcamedy/CandlestickChartScreen/Model/CandlestickPrice.swift
  BithumbYagomAcamedy/CandlestickChartScreen/View/CandlestickInfoTextView.swift
  BithumbYagomAcamedy/CandlestickChartScreen/View/CoinChart.storyboard
Labels: ui, feat

#96 코인 목록 화면 버그 수정
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/CoinListScreen/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/CoinListScreen/Model/CoinListDataManager.swift
  BithumbYagomAcamedy/CoinListScreen/View/CoinListCollectionViewCell.swift
  BithumbYagomAcamedy/CoinListScreen/View/CoinListCollectionViewCell.xib
  BithumbYagomAcamedy/Common/Model/Coin.swift
  BithumbYagomAcamedy/Network/HTTP/Extension/URLRequest+extension.swift
Labels: bug, fix

#95 더보기 화면 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/MoreDetailScreen/Controller/MoreDetailViewController.swift
  BithumbYagomAcamedy/MoreDetailScreen/Model/License.swift
  BithumbYagomAcamedy/MoreDetailScreen/Model/UserInformation.swift
  BithumbYagomAcamedy/MoreDetailScreen/View/MoreDetail.storyboard
  BithumbYagomAcamedy/MoreDetailScreen/View/UserInfoView.swift
  BithumbYagomAcamedy/MoreDetailScreen/View/UserInfoView.xib
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Donggeon.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Donggeon.imageset/Donggeon.jpeg
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Jeha.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Jeha.imageset/Jaeha.jpeg
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Zero.imageset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/UserImage/Zero.imageset/Zero.jpeg
Labels: ui, feat

#100 종가 기준 변경
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/CoinListScreen/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/CoinListScreen/Model/CoinListDataManager.swift
  BithumbYagomAcamedy/Extension/UICollectionViewDiffableDataSource+extension.swift
  BithumbYagomAcamedy/Utility/AlertFactory/NetworkFailAlertPresentable.swift
Labels: fix

#102 입출금 초기 화면 갱신 시 이름순으로 정렬하도록 수정
  BithumbYagomAcamedy/DepositWithdrawalStatusScreen/Model/DepositWithdrawalStatusDataManager.swift
Labels: fix

#103 호가 화면 매수(최고가), 매도(최저가) 뷰 노출 기능
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/OrderbookScreen/Controller/CoinOrderbookViewController.swift
  BithumbYagomAcamedy/OrderbookScreen/Model/CoinOrderbokDataManager.swift
  BithumbYagomAcamedy/OrderbookScreen/View/CoinOrderbook.storyboard
  BithumbYagomAcamedy/OrderbookScreen/View/MaximumMinimumOrderPriceView.swift
Labels: ui, feat

#105 체결내역 화면 버그 수정
  BithumbYagomAcamedy/CandlestickChartScreen/Controller/CoinChartViewController.swift
  BithumbYagomAcamedy/CoinDetailScreen/Controller/CoinDetailPageViewController.swift
  BithumbYagomAcamedy/CoinDetailScreen/Model/PageViewControllerable.swift
  BithumbYagomAcamedy/CoinDetailScreen/View/CoinDetail.storyboard
  BithumbYagomAcamedy/OrderbookScreen/Controller/CoinOrderbookViewController.swift
  BithumbYagomAcamedy/TransactionScreen/Controller/CoinTransactionViewController.swift
  BithumbYagomAcamedy/TransactionScreen/View/CoinTransaction.storyboard
Labels: bug, fix

#107 프로젝트 소개 페이지 구현
  docs/images/bank.png
  docs/images/bankgif.gif
  docs/images/chart.png
  docs/images/chartgif.gif
  docs/images/darkmode.png
  docs/images/favorite.png
  docs/images/favoritegif.gif
  docs/images/listupdatagif.gif
  docs/images/listupdate.png
  docs/images/main.png
  docs/images/orderbook.png
  docs/images/orderbookgif.gif
  docs/images/transaction.png
  docs/images/transactiongif.gif
  docs/index.html
Labels: feat

#110 CandlestickChart 에서 fetch 해올 때 SortDescriptor를 통해 정렬하도록 수정
  BithumbYagomAcamedy/CandlestickChartScreen/Model/CoinChartCoreDataManager.swift
  BithumbYagomAcamedy/CoreData/Entity/CandlestickChart+CoreDataProperties.swift
Labels: fix

#112 셀 가격변동시 스와이프 풀리는 현상 해결
  BithumbYagomAcamedy/CoinListScreen/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/CoinListScreen/Model/CoinListDataManager.swift
  BithumbYagomAcamedy/CoinListScreen/View/CoinListCollectionViewCell.swift
Labels: fix

#114 코인 차트 그래프 세그먼트 컨트롤 색상 변경
  BithumbYagomAcamedy/CandlestickChartScreen/View/CoinChart.storyboard
Labels: ui, fix

#115 HTTP 네트워크 통신 개선
  BithumbYagomAcamedy/CandlestickChartScreen/Model/CoinChartDataManager.swift
  BithumbYagomAcamedy/CoinDetailScreen/Model/CoinDetailDataManager.swift
  BithumbYagomAcamedy/CoinListScreen/Model/CoinListDataManager.swift
  BithumbYagomAcamedy/Common/Model/HTTPValueObject/TransactionValueObject.swift
  BithumbYagomAcamedy/DepositWithdrawalStatusScreen/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/Network/HTTP/HTTPNetworkService.swift
  BithumbYagomAcamedy/OrderbookScreen/Model/CoinOrderbokDataManager.swift
  BithumbYagomAcamedy/TransactionScreen/Model/CoinTransactionDataManager.swift
  BithumbYagomAcamedy/Utility/JSONParser.swift
  BithumbYagomAcamedyTests/JSONParserTest/JSONParserTests.swift
Labels: refactor

#116 README.md 작성
  README.md
Labels: docs
