Repository DonggeonOh/bithumb-techcamp-ios-1st, pull requests merged in 2022-02, with the labels that each got.

#6 JSONParser 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Utility/JSONParser.swift
  BithumbYagomAcamedyTests/JSONParserTests.swift
  BithumbYagomAcamedyTests/Mock Data/TickerJSONFile.json
Labels: feat

#11 네트워크에 필요한 VO 구조체 작성
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Model/ValueObject/AssetsStatusAllValueObject.swift
  BithumbYagomAcamedy/Model/ValueObject/OrderbookValueObject.swift
  BithumbYagomAcamedy/Model/ValueObject/TickerValueObject.swift
  BithumbYagomAcamedy/Model/ValueObject/TickersValueObject.swift
  BithumbYagomAcamedy/Model/ValueObject/TransactionValueObject.swift
Labels: feat

#13 코인 리스트 컬렉션 셀 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.swift
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.xib
Labels: ui, feat

#12 네트워크 통신(HTTP) 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Extension/URLRequest+extension.swift
  BithumbYagomAcamedy/Extension/URLSession+extension.swift
  BithumbYagomAcamedy/Protocol/APIable.swift
  BithumbYagomAcamedy/Utility/NetworkService.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockURLSession.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/NetworkServiceTests.swift
Labels: feat

#17 JSONParser를 테스트하기 위한 테스트 코드 작성
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedyTests/JSONParserTest/JSONParserTests.swift
  BithumbYagomAcamedyTests/JSONParserTest/Mock/AssetsStatusJSONFile.json
  BithumbYagomAcamedyTests/JSONParserTest/Mock/OrderbookJSONFile.json
  BithumbYagomAcamedyTests/JSONParserTest/Mock/TickerJSONFile.json
  BithumbYagomAcamedyTests/JSONParserTest/Mock/TickersJSONFile.json
  BithumbYagomAcamedyTests/JSONParserTest/Mock/TransactionJSONFile.json
  BithumbYagomAcamedyTests/JSONParserTests.swift
Labels: test

#20 입출금 내역 콜렉션 리스트 뷰 xib 추가 및 클래스 초기화
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.swift
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.xib
Labels: ui, feat

#24 CoinList 화면 콜렉션 뷰 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/CoinListDataSource.swift
  BithumbYagomAcamedy/Controller/CoinListViewController.swift
  BithumbYagomAcamedy/View/CoinListView/CoinList.storyboard
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.swift
  BithumbYagomAcamedy/View/CoinListView/CoinListCollectionViewCell.xib
Labels: feat

#25 입출금 현황 화면 레이아웃 작성
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/Resource/Assets.xcassets/StatusColor/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/StatusColor/FailStatus.colorset/Contents.json
  BithumbYagomAcamedy/Resource/Assets.xcassets/StatusColor/SuccessStatus.colorset/Contents.json
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.swift
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.xib
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalStatus.storyboard
Labels: ui, feat

#28 Bithumb assets status API를 이용한 입출금 현황 화면 갱신 기능 추가
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Controller/DepositWithdrawalStatusViewController.swift
  BithumbYagomAcamedy/Model/AssetsStatus.swift
  BithumbYagomAcamedy/Model/DepositWithdrawalStatusDataManager.swift
  BithumbYagomAcamedy/View/DepositWithdrawalStatusView/DepositWithdrawalCollectionViewCell.xib
Labels: ui, feat

#29 네트워크 통신(WebSocket) 구현
  BithumbYagomAcamedy.xcodeproj/project.pbxproj
  BithumbYagomAcamedy/Extension/URLSessionWebSocketTask+extension.swift
  BithumbYagomAcamedy/Protocol/WebSocketServicable.swift
  BithumbYagomAcamedy/Protocol/WebSocketable.swift
  BithumbYagomAcamedy/Utility/Network/HTTPNetworkService.swift
  BithumbYagomAcamedy/Utility/Network/WebSocketService.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockNetworkError.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockURLSession.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockWebSocketService.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/MockWebSocketURLSessionTask.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/Mock/WebSocketSendJSON.json
  BithumbYagomAcamedyTests/NetworkServiceTest/NetworkServiceTests.swift
  BithumbYagomAcamedyTests/NetworkServiceTest/WebSocketServiceTests.swift
Labels: feat
